version: '3'
services:
    nifi:
      image: mkobit/nifi
      volumes:
        - /tmp/nifitmp:/mnt/data
      ports:
        - 8080-8081:8080-8081
      networks:
        - vpcbr

networks:
  vpcbr:
    external:
      name: tc_master_vpcbr

